{
    'name' : 'buildmart ERP',
    'version' : '2.0',
    'summary': 'Invoices & Payments',
    'description': """Feature implementations and customizations for enterprise addons to suit the needs of buildmart India Private Limited""",
    'category': 'All',
    'website': 'https://www.buildmart.com',
    "author": "buildmart India Pvt. Ltd.",
    "maintainer": "Swathi Reddy",
    # 'images' : ['images/**/*'],
    'depends' : ['account',
                 'account_reports',
                 'crm',
                 'helpdesk',
                 'purchase',
                 'stock',
                 'website',
                 'portal',
                 'website_sale',
                 'auth_signup',
                 'mass_mailing',
                 'l10n_in_purchase',
                 'sale_management',
                 'sign',
                 'hr_payroll',
                 'website_blog',
                 'mass_mailing',
                 'l10n_in',
                 'l10n_in_sale',
                ],
    'data': [
        # security & data
        'security/security_groups.xml',
        'security/ir.model.access.csv',

        'data/catalog.xml',
        'data/generic.xml',
        'data/sequence.xml',
        'data/mail_sms_template.xml',
        'data/server_action.xml',
        'data/cron.xml',

        'reports/layout.xml',
        'reports/inv_report.xml',
        'reports/po_report.xml',
        'reports/so_report.xml',
        'reports/report_generic.xml',
        'reports/delivery_report.xml',

        'views/qweb/marketing_mail_templates.xml',
        'views/qweb/code_snippets.xml',
        'views/qweb/generic.xml',
        'views/qweb/login_signup.xml',
        'views/qweb/shop.xml',
        'views/qweb/portal.xml',

        'views/model/notifications.xml',
        'views/model/homepage.xml',
        'views/model/partner.xml',
        'views/model/ecomm_categ.xml',
        'views/model/product.xml',
        'views/model/sale_order.xml',
        'views/model/enquiry.xml',
        'views/model/generic.xml',
        'views/model/rfq_view.xml',
        'views/model/company.xml',
        'views/model/move.xml',
        'views/model/purchase.xml',
        'views/model/seo.xml',
        'views/model/generic_msg.xml',

        'wizards/generic.xml',
        'wizards/res_config_settings.xml',
    ],
    'demo': [
    ],
    'installable': True,
    'auto_install': False,
    'assets': {
        'web.assets_frontend': [
            'buildmart/static/src/js/*',
            'buildmart/static/src/js/plugins/*',
            'buildmart/static/src/scss/*',
        ],
        'web.assets_qweb': [
            'buildmart/static/src/legacy/xml/**/*',
        ],
        'web.assets_backend': [
            'buildmart/static/src/legacy/widgets/grid_view.js',
            'buildmart/static/src/backend/js/account_report.js',
            
        ],
    },
}
